app = 'darkfeed'
primary_region = 'iad'

[build]
  dockerfile = 'Containerfile'
  ignorefile = '.containerignore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[env]
  FEED_ACCOUNT_PDS = 'bsky.social'
  FEED_ACCOUNT_DID = 'did:plc:zhxv5pxpmojhnvaqy4mwailv'
  HOSTNAME = 'darkfeed.fly.dev'
